# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AcePerl
version:      1.91
version_from: Ace.pm
installdirs:  site
requires:
    Cache::Cache:                  1.03
    Digest::MD5:                   2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
